# This is a basic workflow to help you get started with Actions

name: Getting started with maven

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "master" ]
  # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Step2- Setup the jdk1.8
      - uses: actions/setup-java@v2
        with:
         java-version: 1.8

      - name: Step3- Build Maven project
        run:  mvn -B package --file pom.xml 
          
      -name: Step4- list cureent directory
       run: ls -a
       
      -name: step5- what is in target folder
       run: 
          cd target
          ls -a
          
